### ISSUE TITLE
Add optional maxNodes to exchange */search rest api's

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#233] opened 2019-10-07 14:01 UTC
Add this optional field to the input body of the search api's. This would enable the callers only get a reasonable number of nodes in the response in an environment in which there are 1000's of nodes. Talk to the developers that use these search api's to prioritize which ones need it the most, or will actually use this option.

For the pattern and business policy /search APIs, dave would like each agbot to get a different segment of the list until the whole list has been returned to someone, then start fresh again. This will require some significant design.

**Comment by sf2ne** [comment] 2020-06-08 14:21
Duplicate of: https://github.com/open-horizon/exchange-api/issues/310

**Closed by sf2ne** 2020-06-08 14:21 UTC
Labels: perf
