### ISSUE TITLE
Requesting simplification of the error message for a bad org ID.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/exchange-api#257] opened 2019-12-18 19:32 UTC
If you make a typographical in your org ID, you will get this complex error message:```
hzn exchange user list 
Error: bad HTTP code 500 from GET https://edge3211.slayer.icp:10030/ec-exchange/v1/orgs/edge3211.slayer.icp/users/iamapikey, output: {"code":"internal_error","msg":"error creating user edge3211.slayer.icp/admin : ERROR: insert or update on table \"users\" violates foreign key constraint \"orgid_fk\"\n  Detail: Key (orgid)=(edge3211.slayer.icp) is not present in table \"orgs\"."}```
Could we change that to something that looks a lot more like "org id not valid"? Maybe just show the "detail" part, and leave out the table names?

**Comment by bmpotter** [comment] 2020-01-15 17:09
This is a duplicate of https://github.com/open-horizon/exchange-api/issues/221

**Closed by bmpotter** 2020-01-15 17:09 UTC
