### ISSUE TITLE
Exchange read only database connections

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#439] opened 2020-11-11 15:10 UTC
Something happens in the database and some of the exchange's db connections will get stuck in a read only state. This obviously causes a bunch of problems. Our current fix for it is to have a configurable timeout for all connections where all connections will have an expiration time. This should ensure that if a connection does get stuck in a read-only state it should expire on its own and not require an exchange restart (which is the only other solution to this problem). We have been unable to verify if this fix works though. We also have been unable to reproduce this problem on purpose and are unsure of what ultimately causes it.

**Comment by omega2733** [comment] 2020-11-11 15:18
We've seen this issue hit in roks-stg and in scale (during the same weekend) at one point using the same DB connections (remote IBM Cloud DB's). We so far have not seen a recurrence of this issue in any environment that's live in our test env's and don't understand enough about the issue to attempt a reproduction.

I would recommend if we don't see this happen again for a long period of time we can likely close this issue if we're unable to find any reproduction path since it's likely a corner case or edge case. The big thing to test here is to try and cause the READONLY error to come up again and ensure the current fix works as we expect so the exchange gracefully handles this as Sadiyah has mentioned above.

**Closed** 2024-11-18 14:44 UTC
